"""outreach campaigns

Revision ID: d2fdf6c469fe
Revises: f1d67bf5890a
Create Date: 2026-09-29 09:27:29.087233

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2fdf6c469fe"
down_revision: str | Sequence[str] | None = "f1d67bf5890a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaigns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("coverage_run_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("district", sa.String(length=64), nullable=True),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["officials.id"], name=op.f("fk_campaigns_approved_by_officials")
        ),
        sa.ForeignKeyConstraint(
            ["coverage_run_id"],
            ["coverage_runs.id"],
            name=op.f("fk_campaigns_coverage_run_id_coverage_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["officials.id"], name=op.f("fk_campaigns_created_by_officials")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
    )
    op.create_index(op.f("ix_campaigns_state"), "campaigns", ["state"], unique=False)
    op.create_table(
        "campaign_targets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("student_ref", sa.String(length=64), nullable=False),
        sa.Column("udise_code", sa.String(length=32), nullable=False),
        sa.Column("district", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_targets_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_targets")),
    )
    op.create_index(
        op.f("ix_campaign_targets_campaign_id"), "campaign_targets", ["campaign_id"], unique=False
    )
    op.create_index(
        "uq_campaign_targets_student",
        "campaign_targets",
        ["campaign_id", "student_ref"],
        unique=True,
    )
    op.create_table(
        "outreach_links",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("udise_code", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_outreach_links_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_outreach_links")),
    )
    op.create_index(
        op.f("ix_outreach_links_campaign_id"), "outreach_links", ["campaign_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outreach_links_campaign_id"), table_name="outreach_links")
    op.drop_table("outreach_links")
    op.drop_index("uq_campaign_targets_student", table_name="campaign_targets")
    op.drop_index(op.f("ix_campaign_targets_campaign_id"), table_name="campaign_targets")
    op.drop_table("campaign_targets")
    op.drop_index(op.f("ix_campaigns_state"), table_name="campaigns")
    op.drop_table("campaigns")
    # ### end Alembic commands ###
