"""identities documents proofs exceptions consents

Revision ID: dbfbc112706d
Revises: d804e8d7db80
Create Date: 2026-09-29 03:50:26.227889

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dbfbc112706d"
down_revision: str | Sequence[str] | None = "d804e8d7db80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_consents_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consents")),
    )
    op.create_index(op.f("ix_consents_student_id"), "consents", ["student_id"], unique=False)
    op.create_table(
        "digilocker_requests",
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("code_verifier", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_digilocker_requests_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("state", name=op.f("pk_digilocker_requests")),
    )
    op.create_table(
        "identities",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("digilocker_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(length=8), nullable=True),
        sa.Column("reference_key", sa.String(length=128), nullable=False),
        sa.Column(
            "linked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_identities_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("student_id", name=op.f("pk_identities")),
        sa.UniqueConstraint("digilocker_id", name=op.f("uq_identities_digilocker_id")),
    )
    op.create_table(
        "proofs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("fact_name", sa.String(length=64), nullable=False),
        sa.Column(
            "payload",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("signature", sa.String(length=128), nullable=False),
        sa.Column("key_id", sa.String(length=32), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_proofs_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proofs")),
    )
    op.create_index(op.f("ix_proofs_student_id"), "proofs", ["student_id"], unique=False)
    op.create_table(
        "referenced_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("uri", sa.String(length=255), nullable=False),
        sa.Column("doctype", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("issuer", sa.String(length=200), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_referenced_documents_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_referenced_documents")),
    )
    op.create_index(
        "uq_referenced_documents_student_uri",
        "referenced_documents",
        ["student_id", "uri"],
        unique=True,
    )
    op.create_table(
        "verification_exceptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("fact_name", sa.String(length=64), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("remedy", sa.Text(), nullable=True),
        sa.Column(
            "evidence",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_verification_exceptions_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_exceptions")),
    )
    op.create_index(
        op.f("ix_verification_exceptions_status"),
        "verification_exceptions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_exceptions_student_id"),
        "verification_exceptions",
        ["student_id"],
        unique=False,
    )
    op.add_column("fact_records", sa.Column("proof_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_fact_records_proof_id_proofs"),
        "fact_records",
        "proofs",
        ["proof_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_fact_records_proof_id_proofs"), "fact_records", type_="foreignkey")
    op.drop_column("fact_records", "proof_id")
    op.drop_index(
        op.f("ix_verification_exceptions_student_id"), table_name="verification_exceptions"
    )
    op.drop_index(op.f("ix_verification_exceptions_status"), table_name="verification_exceptions")
    op.drop_table("verification_exceptions")
    op.drop_index("uq_referenced_documents_student_uri", table_name="referenced_documents")
    op.drop_table("referenced_documents")
    op.drop_index(op.f("ix_proofs_student_id"), table_name="proofs")
    op.drop_table("proofs")
    op.drop_table("identities")
    op.drop_table("digilocker_requests")
    op.drop_index(op.f("ix_consents_student_id"), table_name="consents")
    op.drop_table("consents")
    # ### end Alembic commands ###
