"""phone calls

Revision ID: c3a99dff96fa
Revises: a8c80237a62f
Create Date: 2026-09-29 09:55:03.833711

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c3a99dff96fa"
down_revision: str | Sequence[str] | None = "a8c80237a62f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "phone_calls",
        sa.Column("call_sid", sa.String(length=64), nullable=False),
        sa.Column("phone", sa.String(length=16), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.Column("stage", sa.String(length=16), nullable=False),
        sa.Column(
            "keys",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_phone_calls_student_id_students"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("call_sid", name=op.f("pk_phone_calls")),
    )
    op.create_index(op.f("ix_phone_calls_student_id"), "phone_calls", ["student_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_phone_calls_student_id"), table_name="phone_calls")
    op.drop_table("phone_calls")
    # ### end Alembic commands ###
