"""uploaded documents

Revision ID: f1d67bf5890a
Revises: 92c9083e98df
Create Date: 2026-09-29 09:03:22.231521

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f1d67bf5890a"
down_revision: str | Sequence[str] | None = "92c9083e98df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uploaded_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.String(length=200), nullable=True),
        sa.Column("key_id", sa.String(length=32), nullable=False),
        sa.Column(
            "fields",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_uploaded_documents_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uploaded_documents")),
    )
    op.create_index(
        op.f("ix_uploaded_documents_delete_after"),
        "uploaded_documents",
        ["delete_after"],
        unique=False,
    )
    op.create_index(
        op.f("ix_uploaded_documents_student_id"), "uploaded_documents", ["student_id"], unique=False
    )
    op.add_column(
        "verification_exceptions", sa.Column("state", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "verification_exceptions", sa.Column("district", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "verification_exceptions", sa.Column("uploaded_document_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        op.f("ix_verification_exceptions_uploaded_document_id"),
        "verification_exceptions",
        ["uploaded_document_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_verification_exceptions_uploaded_document_id_uploaded_documents"),
        "verification_exceptions",
        "uploaded_documents",
        ["uploaded_document_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_verification_exceptions_uploaded_document_id_uploaded_documents"),
        "verification_exceptions",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_verification_exceptions_uploaded_document_id"),
        table_name="verification_exceptions",
    )
    op.drop_column("verification_exceptions", "uploaded_document_id")
    op.drop_column("verification_exceptions", "district")
    op.drop_column("verification_exceptions", "state")
    op.drop_index(op.f("ix_uploaded_documents_student_id"), table_name="uploaded_documents")
    op.drop_index(op.f("ix_uploaded_documents_delete_after"), table_name="uploaded_documents")
    op.drop_table("uploaded_documents")
    # ### end Alembic commands ###
