"""rule drafts

Revision ID: bed3fd94940e
Revises: 1f553142c40b
Create Date: 2026-09-29 10:05:58.573562

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bed3fd94940e"
down_revision: str | Sequence[str] | None = "1f553142c40b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rule_drafts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("scheme_id", sa.String(length=32), nullable=False),
        sa.Column("parameter", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("current_value", sa.Float(), nullable=False),
        sa.Column("found_value", sa.Float(), nullable=False),
        sa.Column("source_title", sa.String(length=200), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("patch", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["officials.id"], name=op.f("fk_rule_drafts_created_by_officials")
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"], ["officials.id"], name=op.f("fk_rule_drafts_decided_by_officials")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_drafts")),
    )
    op.create_index(op.f("ix_rule_drafts_status"), "rule_drafts", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rule_drafts_status"), table_name="rule_drafts")
    op.drop_table("rule_drafts")
    # ### end Alembic commands ###
