"""application snapshots

Revision ID: b5cb6834dd97
Revises: dbfbc112706d
Create Date: 2026-09-29 03:59:23.059145

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b5cb6834dd97"
down_revision: str | Sequence[str] | None = "dbfbc112706d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("source_system", sa.String(length=16), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("scheme_id", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("waiting_on", sa.String(length=32), nullable=True),
        sa.Column("since", sa.Date(), nullable=True),
        sa.Column(
            "record",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_application_snapshots_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_snapshots")),
    )
    op.create_index(
        op.f("ix_application_snapshots_stage"), "application_snapshots", ["stage"], unique=False
    )
    op.create_index(
        "uq_application_snapshots_student_source_external",
        "application_snapshots",
        ["student_id", "source_system", "external_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_application_snapshots_student_source_external", table_name="application_snapshots"
    )
    op.drop_index(op.f("ix_application_snapshots_stage"), table_name="application_snapshots")
    op.drop_table("application_snapshots")
    # ### end Alembic commands ###
