"""grievances

Revision ID: a8c80237a62f
Revises: d2fdf6c469fe
Create Date: 2026-09-29 09:42:28.347146

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8c80237a62f"
down_revision: str | Sequence[str] | None = "d2fdf6c469fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grievances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("subject_key", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("registration_number", sa.String(length=40), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("reply", sa.Text(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_grievances_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grievances")),
        sa.UniqueConstraint("registration_number", name=op.f("uq_grievances_registration_number")),
    )
    op.create_index(op.f("ix_grievances_student_id"), "grievances", ["student_id"], unique=False)
    op.create_index(
        "uq_grievances_subject", "grievances", ["student_id", "subject_key"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_grievances_subject", table_name="grievances")
    op.drop_index(op.f("ix_grievances_student_id"), table_name="grievances")
    op.drop_table("grievances")
    # ### end Alembic commands ###
