"""nudges

Revision ID: 0ab4b0d0f8df
Revises: 2c90a1feb725
Create Date: 2026-09-29 08:36:33.317647

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ab4b0d0f8df"
down_revision: str | Sequence[str] | None = "2c90a1feb725"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nudges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("audience", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=True),
        sa.Column("state", sa.String(length=64), nullable=True),
        sa.Column("district", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_nudges_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nudges")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_nudges_dedupe_key")),
    )
    op.create_index(op.f("ix_nudges_status"), "nudges", ["status"], unique=False)
    op.create_index(op.f("ix_nudges_student_id"), "nudges", ["student_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_nudges_student_id"), table_name="nudges")
    op.drop_index(op.f("ix_nudges_status"), table_name="nudges")
    op.drop_table("nudges")
    # ### end Alembic commands ###
