"""family links

Revision ID: 92c9083e98df
Revises: 0ab4b0d0f8df
Create Date: 2026-09-29 08:51:33.870516

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92c9083e98df"
down_revision: str | Sequence[str] | None = "0ab4b0d0f8df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "family_invites",
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_family_invites_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("code_hash", name=op.f("pk_family_invites")),
    )
    op.create_table(
        "guardian_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("guardian_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guardian_id"],
            ["students.id"],
            name=op.f("fk_guardian_links_guardian_id_students"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_guardian_links_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guardian_links")),
    )
    op.create_index(
        op.f("ix_guardian_links_guardian_id"), "guardian_links", ["guardian_id"], unique=False
    )
    op.create_index(
        op.f("ix_guardian_links_student_id"), "guardian_links", ["student_id"], unique=False
    )
    op.create_index(
        "uq_guardian_links_pair", "guardian_links", ["guardian_id", "student_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_guardian_links_pair", table_name="guardian_links")
    op.drop_index(op.f("ix_guardian_links_student_id"), table_name="guardian_links")
    op.drop_index(op.f("ix_guardian_links_guardian_id"), table_name="guardian_links")
    op.drop_table("guardian_links")
    op.drop_table("family_invites")
    # ### end Alembic commands ###
