"""facilitators

Revision ID: 2447f947e7e1
Revises: bed3fd94940e
Create Date: 2026-09-29 13:54:07.261764

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2447f947e7e1"
down_revision: str | Sequence[str] | None = "bed3fd94940e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "facilitators",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("organisation", sa.String(length=200), nullable=False),
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("district", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["students.id"],
            name=op.f("fk_facilitators_account_id_students"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"], ["officials.id"], name=op.f("fk_facilitators_decided_by_officials")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_facilitators")),
        sa.UniqueConstraint("account_id", name=op.f("uq_facilitators_account_id")),
    )
    op.create_index(op.f("ix_facilitators_status"), "facilitators", ["status"], unique=False)
    op.create_table(
        "facilitation_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("facilitator_id", sa.Uuid(), nullable=False),
        sa.Column("phone", sa.String(length=16), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["facilitator_id"],
            ["facilitators.id"],
            name=op.f("fk_facilitation_requests_facilitator_id_facilitators"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_facilitation_requests")),
    )
    op.create_index(
        op.f("ix_facilitation_requests_facilitator_id"),
        "facilitation_requests",
        ["facilitator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_facilitation_requests_phone"), "facilitation_requests", ["phone"], unique=False
    )
    op.create_table(
        "facilitator_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("facilitator_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["facilitator_id"],
            ["facilitators.id"],
            name=op.f("fk_facilitator_links_facilitator_id_facilitators"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_facilitator_links_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_facilitator_links")),
    )
    op.create_index(
        op.f("ix_facilitator_links_facilitator_id"),
        "facilitator_links",
        ["facilitator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_facilitator_links_student_id"), "facilitator_links", ["student_id"], unique=False
    )
    op.create_index(
        "uq_facilitator_links_pair",
        "facilitator_links",
        ["facilitator_id", "student_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_facilitator_links_pair", table_name="facilitator_links")
    op.drop_index(op.f("ix_facilitator_links_student_id"), table_name="facilitator_links")
    op.drop_index(op.f("ix_facilitator_links_facilitator_id"), table_name="facilitator_links")
    op.drop_table("facilitator_links")
    op.drop_index(op.f("ix_facilitation_requests_phone"), table_name="facilitation_requests")
    op.drop_index(
        op.f("ix_facilitation_requests_facilitator_id"), table_name="facilitation_requests"
    )
    op.drop_table("facilitation_requests")
    op.drop_index(op.f("ix_facilitators_status"), table_name="facilitators")
    op.drop_table("facilitators")
    # ### end Alembic commands ###
