"""outbound calls

Revision ID: 1f553142c40b
Revises: c3a99dff96fa
Create Date: 2026-09-29 09:59:40.221919

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f553142c40b"
down_revision: str | Sequence[str] | None = "c3a99dff96fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "phone_calls",
        sa.Column("direction", sa.String(length=8), nullable=False, server_default="inbound"),
    )
    op.add_column("phone_calls", sa.Column("topic", sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("phone_calls", "topic")
    op.drop_column("phone_calls", "direction")
    # ### end Alembic commands ###
